// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SculptAR",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "SculptAR",
            targets: ["AppModule"],
            bundleIdentifier: "francesco.wwdc-3",
            teamIdentifier: "C598U6DJ3G",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "ar")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/maxxfrazer/FocusEntity", "2.0.0"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FocusEntity", package: "focusentity")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)